module.exports = {
  REACT_APP_CLIENT_ID: process.env.REACT_APP_CLIENT_ID,
  BASE_URL: process.env.BASE_URL,
  MONGO_CONNECTION_STRING: process.env.MONGO_CONNECTION_STRING,
  COOKIE_SECRET_KEY_1: process.env.COOKIE_SECRET_KEY_1,
  COOKIE_SECRET_KEY_2: process.env.COOKIE_SECRET_KEY_2,
};
